var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
define(["require", "exports", "./lib/countries", "./lib/countries", "./lib"], function (require, exports, countries, countries_1, lib_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    countries = __importStar(countries);
    exports.countries = countries;
    exports.austria = countries_1.austria;
    exports.belgium = countries_1.belgium;
    exports.bulgaria = countries_1.bulgaria;
    exports.croatia = countries_1.croatia;
    exports.cyprus = countries_1.cyprus;
    exports.czechRepublic = countries_1.czechRepublic;
    exports.denmark = countries_1.denmark;
    exports.estonia = countries_1.estonia;
    exports.europe = countries_1.europe;
    exports.finland = countries_1.finland;
    exports.france = countries_1.france;
    exports.germany = countries_1.germany;
    exports.greece = countries_1.greece;
    exports.hungary = countries_1.hungary;
    exports.ireland = countries_1.ireland;
    exports.italy = countries_1.italy;
    exports.latvia = countries_1.latvia;
    exports.lithuania = countries_1.lithuania;
    exports.luxembourg = countries_1.luxembourg;
    exports.malta = countries_1.malta;
    exports.netherlands = countries_1.netherlands;
    exports.norway = countries_1.norway;
    exports.poland = countries_1.poland;
    exports.portugal = countries_1.portugal;
    exports.romania = countries_1.romania;
    exports.russia = countries_1.russia;
    exports.serbia = countries_1.serbia;
    exports.slovakiaRepublic = countries_1.slovakiaRepublic;
    exports.slovenia = countries_1.slovenia;
    exports.spain = countries_1.spain;
    exports.sweden = countries_1.sweden;
    exports.switzerland = countries_1.switzerland;
    exports.unitedKingdom = countries_1.unitedKingdom;
    exports.checkVAT = lib_1.checkVAT;
});
