define(["require", "exports", "./andorra", "./austria", "./belgium", "./brazil", "./bulgaria", "./croatiat", "./cyprus", "./czechRepublic", "./denmark", "./estonia", "./europe", "./finland", "./france", "./germany", "./greece", "./hungary", "./ireland", "./italy", "./latvia", "./lithuania", "./luxembourg", "./malta", "./netherlands", "./norway", "./poland", "./portugal", "./romania", "./russia", "./serbia", "./slovakiaRepublic", "./slovenia", "./spain", "./sweden", "./switzerland", "./unitedKingdom"], function (require, exports, andorra_1, austria_1, belgium_1, brazil_1, bulgaria_1, croatiat_1, cyprus_1, czechRepublic_1, denmark_1, estonia_1, europe_1, finland_1, france_1, germany_1, greece_1, hungary_1, ireland_1, italy_1, latvia_1, lithuania_1, luxembourg_1, malta_1, netherlands_1, norway_1, poland_1, portugal_1, romania_1, russia_1, serbia_1, slovakiaRepublic_1, slovenia_1, spain_1, sweden_1, switzerland_1, unitedKingdom_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.unitedKingdom = exports.switzerland = exports.sweden = exports.spain = exports.slovenia = exports.slovakiaRepublic = exports.serbia = exports.russia = exports.romania = exports.portugal = exports.poland = exports.norway = exports.netherlands = exports.malta = exports.luxembourg = exports.lithuania = exports.latvia = exports.italy = exports.ireland = exports.hungary = exports.greece = exports.germany = exports.france = exports.finland = exports.europe = exports.estonia = exports.denmark = exports.czechRepublic = exports.cyprus = exports.croatia = exports.bulgaria = exports.brazil = exports.belgium = exports.austria = exports.andorra = void 0;
    Object.defineProperty(exports, "andorra", { enumerable: true, get: function () { return andorra_1.andorra; } });
    Object.defineProperty(exports, "austria", { enumerable: true, get: function () { return austria_1.austria; } });
    Object.defineProperty(exports, "belgium", { enumerable: true, get: function () { return belgium_1.belgium; } });
    Object.defineProperty(exports, "brazil", { enumerable: true, get: function () { return brazil_1.brazil; } });
    Object.defineProperty(exports, "bulgaria", { enumerable: true, get: function () { return bulgaria_1.bulgaria; } });
    Object.defineProperty(exports, "croatia", { enumerable: true, get: function () { return croatiat_1.croatia; } });
    Object.defineProperty(exports, "cyprus", { enumerable: true, get: function () { return cyprus_1.cyprus; } });
    Object.defineProperty(exports, "czechRepublic", { enumerable: true, get: function () { return czechRepublic_1.czechRepublic; } });
    Object.defineProperty(exports, "denmark", { enumerable: true, get: function () { return denmark_1.denmark; } });
    Object.defineProperty(exports, "estonia", { enumerable: true, get: function () { return estonia_1.estonia; } });
    Object.defineProperty(exports, "europe", { enumerable: true, get: function () { return europe_1.europe; } });
    Object.defineProperty(exports, "finland", { enumerable: true, get: function () { return finland_1.finland; } });
    Object.defineProperty(exports, "france", { enumerable: true, get: function () { return france_1.france; } });
    Object.defineProperty(exports, "germany", { enumerable: true, get: function () { return germany_1.germany; } });
    Object.defineProperty(exports, "greece", { enumerable: true, get: function () { return greece_1.greece; } });
    Object.defineProperty(exports, "hungary", { enumerable: true, get: function () { return hungary_1.hungary; } });
    Object.defineProperty(exports, "ireland", { enumerable: true, get: function () { return ireland_1.ireland; } });
    Object.defineProperty(exports, "italy", { enumerable: true, get: function () { return italy_1.italy; } });
    Object.defineProperty(exports, "latvia", { enumerable: true, get: function () { return latvia_1.latvia; } });
    Object.defineProperty(exports, "lithuania", { enumerable: true, get: function () { return lithuania_1.lithuania; } });
    Object.defineProperty(exports, "luxembourg", { enumerable: true, get: function () { return luxembourg_1.luxembourg; } });
    Object.defineProperty(exports, "malta", { enumerable: true, get: function () { return malta_1.malta; } });
    Object.defineProperty(exports, "netherlands", { enumerable: true, get: function () { return netherlands_1.netherlands; } });
    Object.defineProperty(exports, "norway", { enumerable: true, get: function () { return norway_1.norway; } });
    Object.defineProperty(exports, "poland", { enumerable: true, get: function () { return poland_1.poland; } });
    Object.defineProperty(exports, "portugal", { enumerable: true, get: function () { return portugal_1.portugal; } });
    Object.defineProperty(exports, "romania", { enumerable: true, get: function () { return romania_1.romania; } });
    Object.defineProperty(exports, "russia", { enumerable: true, get: function () { return russia_1.russia; } });
    Object.defineProperty(exports, "serbia", { enumerable: true, get: function () { return serbia_1.serbia; } });
    Object.defineProperty(exports, "slovakiaRepublic", { enumerable: true, get: function () { return slovakiaRepublic_1.slovakiaRepublic; } });
    Object.defineProperty(exports, "slovenia", { enumerable: true, get: function () { return slovenia_1.slovenia; } });
    Object.defineProperty(exports, "spain", { enumerable: true, get: function () { return spain_1.spain; } });
    Object.defineProperty(exports, "sweden", { enumerable: true, get: function () { return sweden_1.sweden; } });
    Object.defineProperty(exports, "switzerland", { enumerable: true, get: function () { return switzerland_1.switzerland; } });
    Object.defineProperty(exports, "unitedKingdom", { enumerable: true, get: function () { return unitedKingdom_1.unitedKingdom; } });
});
