(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "./lib/countries/austria", "./lib/countries/belgium", "./lib/countries/bulgaria", "./lib/countries/croatiat", "./lib/countries/cyprus", "./lib/countries/czechRepublic", "./lib/countries/denmark", "./lib/countries/estonia", "./lib/countries/europe", "./lib/countries/finland", "./lib/countries/france", "./lib/countries/germany", "./lib/countries/greece", "./lib/countries/hungary", "./lib/countries/ireland", "./lib/countries/italy", "./lib/countries/latvia", "./lib/countries/lithuania", "./lib/countries/luxembourg", "./lib/countries/malta", "./lib/countries/netherlands", "./lib/countries/norway", "./lib/countries/poland", "./lib/countries/portugal", "./lib/countries/romania", "./lib/countries/russia", "./lib/countries/serbia", "./lib/countries/slovakiaRepublic", "./lib/countries/slovenia", "./lib/countries/spain", "./lib/countries/sweden", "./lib/countries/switzerland", "./lib/countries/unitedKingdom", "./lib"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var austria_1 = require("./lib/countries/austria");
    exports.austria = austria_1.austria;
    var belgium_1 = require("./lib/countries/belgium");
    exports.belgium = belgium_1.belgium;
    var bulgaria_1 = require("./lib/countries/bulgaria");
    exports.bulgaria = bulgaria_1.bulgaria;
    var croatiat_1 = require("./lib/countries/croatiat");
    exports.croatia = croatiat_1.croatia;
    var cyprus_1 = require("./lib/countries/cyprus");
    exports.cyprus = cyprus_1.cyprus;
    var czechRepublic_1 = require("./lib/countries/czechRepublic");
    exports.czechRepublic = czechRepublic_1.czechRepublic;
    var denmark_1 = require("./lib/countries/denmark");
    exports.denmark = denmark_1.denmark;
    var estonia_1 = require("./lib/countries/estonia");
    exports.estonia = estonia_1.estonia;
    var europe_1 = require("./lib/countries/europe");
    exports.europe = europe_1.europe;
    var finland_1 = require("./lib/countries/finland");
    exports.finland = finland_1.finland;
    var france_1 = require("./lib/countries/france");
    exports.france = france_1.france;
    var germany_1 = require("./lib/countries/germany");
    exports.germany = germany_1.germany;
    var greece_1 = require("./lib/countries/greece");
    exports.greece = greece_1.greece;
    var hungary_1 = require("./lib/countries/hungary");
    exports.hungary = hungary_1.hungary;
    var ireland_1 = require("./lib/countries/ireland");
    exports.ireland = ireland_1.ireland;
    var italy_1 = require("./lib/countries/italy");
    exports.italy = italy_1.italy;
    var latvia_1 = require("./lib/countries/latvia");
    exports.latvia = latvia_1.latvia;
    var lithuania_1 = require("./lib/countries/lithuania");
    exports.lithuania = lithuania_1.lithuania;
    var luxembourg_1 = require("./lib/countries/luxembourg");
    exports.luxembourg = luxembourg_1.luxembourg;
    var malta_1 = require("./lib/countries/malta");
    exports.malta = malta_1.malta;
    var netherlands_1 = require("./lib/countries/netherlands");
    exports.netherlands = netherlands_1.netherlands;
    var norway_1 = require("./lib/countries/norway");
    exports.norway = norway_1.norway;
    var poland_1 = require("./lib/countries/poland");
    exports.poland = poland_1.poland;
    var portugal_1 = require("./lib/countries/portugal");
    exports.portugal = portugal_1.portugal;
    var romania_1 = require("./lib/countries/romania");
    exports.romania = romania_1.romania;
    var russia_1 = require("./lib/countries/russia");
    exports.russia = russia_1.russia;
    var serbia_1 = require("./lib/countries/serbia");
    exports.serbia = serbia_1.serbia;
    var slovakiaRepublic_1 = require("./lib/countries/slovakiaRepublic");
    exports.slovakiaRepublic = slovakiaRepublic_1.slovakiaRepublic;
    var slovenia_1 = require("./lib/countries/slovenia");
    exports.slovenia = slovenia_1.slovenia;
    var spain_1 = require("./lib/countries/spain");
    exports.spain = spain_1.spain;
    var sweden_1 = require("./lib/countries/sweden");
    exports.sweden = sweden_1.sweden;
    var switzerland_1 = require("./lib/countries/switzerland");
    exports.switzerland = switzerland_1.switzerland;
    var unitedKingdom_1 = require("./lib/countries/unitedKingdom");
    exports.unitedKingdom = unitedKingdom_1.unitedKingdom;
    var lib_1 = require("./lib");
    exports.checkVAT = lib_1.checkVAT;
});
